### ISSUE TITLE
Integration is not loading

### ISSUE THREAD

**Issue by SchangDK** [J-Lindvig/Bibliotek_dk#5]
I just added the custom repository to HACS and restarted HA and all looks well and good. That is, until I try to add it under Integrations, then the launch screens shows and just keeps spinning with no end in sight. Any tips on how to proceed, or is this because something was deprecated in the last HA update as mentioned in one of the other issues?

BR Michael

**Comment by larsalthof** [comment]
#7 Should fix this

**Comment by SchangDK** [comment]
Hi Lars, 

Thank you for looking into this, but after updating the HACS and restarting HA, I still have the same spinning circle. Do you have any tips on how to troubleshoot? :o)

**Comment by larsalthof** [comment]
Hi, please add this to your configuration.yaml and tell me, what the bibliotek_dk integrations writes in the log file.
```
logger:
  default: warning
  logs:
    custom_components.bibliotek_dk: debug

```

**Comment by larsalthof** [comment]
@SchangDK At what point in the setup does it hang?
If it hangs before getting to the setup dialog, it can be because you do not have a location set within DK for your HA instance. See #6

**Comment by larsalthof** [comment]
Please try v0.3.9

**Comment by SchangDK** [comment]
Hi, v0.3.9 works!! I don't know which part made it work, but now I was able to successfully sign in! 

And sorry for the late reply! Appreciate the work you are doing!
